# Часть 1

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$; \\
   $AB$ не определено, т.к. число столбцов матрицы  𝐴  не равно числу строк матрицы  𝐵 . \\
   $BA$ не определено, т.к. число столбцов матрицы  B  не равно числу строк матрицы  A.
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$; \\
   $AB$ определено, т.к. число столбцов матрицы  𝐴  равно числу строк матрицы  𝐵. Размерность полученной матрицыы $2\times 3$. \\
   $BA$ не определено, т.к. число столбцов матрицы  B  не равно числу строк матрицы  A.
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$; \\
   $AB$ определено, т.к. число столбцов матрицы  𝐴  равно числу строк матрицы  𝐵. Размерность полученной матрицыы $8\times 8$. \\
   $BA$ определено, т.к. число столбцов матрицы  B  равно числу строк матрицы  A. Размерность полученной матрицыы $3\times 3$. \\
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$. \\
   $AB$ определено, т.к. число столбцов матрицы  𝐴  равно числу строк матрицы  𝐵. Размерность полученной матрицыы $4\times 4$. \\
   $BA$ определено, т.к. число столбцов матрицы  B  равно числу строк матрицы  A. Размерность полученной матрицыы $4\times 4$. \\

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$ \\
$A+B=\begin{pmatrix}
1+4 & -2+(-1)\\ 
3+0 & 0+5
\end{pmatrix}=\begin{pmatrix}
5 & -3\\ 
3 & 5
\end{pmatrix}$ \\
$AB=\begin{pmatrix}
1\cdot4+(-2)\cdot0 & 1\cdot(-1)+(-2)\cdot5\\ 
3\cdot4+0\cdot0 & 3\cdot(-1)+0\cdot5
\end{pmatrix}=\begin{pmatrix}
4 & -11\\ 
12 & -3
\end{pmatrix}$ \\
$BA=\begin{pmatrix}
4\cdot1+(-1)\cdot3 & 4\cdot(-2)+(-1)\cdot0\\ 
0\cdot1+5\cdot3 & 0\cdot(-2)+5\cdot0
\end{pmatrix}=\begin{pmatrix}
1 & -8\\ 
15 & 0
\end{pmatrix}$

In [ ]:
import numpy as np

In [ ]:
A=np.array([[1,-2],[3,0]])
B=np.array([[4,-1],[0,5]])

print(f'A+B=\n{A+B}')
print(f'AB=\n{np.dot(A, B)}')
print(f'BA=\n{np.dot(B, A)}')

A+B=
[[ 5 -3]
 [ 3  5]]
AB=
[[  4 -11]
 [ 12  -3]]
BA=
[[ 1 -8]
 [15  0]]


__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$ \\
$3A-2B+4C=3\cdot\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}-2\cdot\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}+4\cdot\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}=\begin{pmatrix}
3 & 21\\ 
9 & -18
\end{pmatrix}+\begin{pmatrix}
0 & -10\\ 
-4 & 2
\end{pmatrix}+\begin{pmatrix}
8 & -16\\ 
4 & 4
\end{pmatrix}=\begin{pmatrix}
11 & -5\\ 
9 & -12
\end{pmatrix}$

In [ ]:
A = np.array([[1,7],[3, -6]])
B = np.array([[0,5],[2, -1]])
C = np.array([[2,-4],[1, 1]])

print(f'3A-2B+4C=\n{3*A - 2*B + 4*C}')

3A-2B+4C=
[[ 11  -5]
 [  9 -12]]


__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$. \\
$A^T=\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix}$ \\
$AA^{T}=\begin{pmatrix}
4\cdot4+1\cdot1 & 4\cdot5+1\cdot(-2) & 4\cdot2+1\cdot3\\ 
5\cdot4+(-2)\cdot1 & 5\cdot5+(-2)\cdot(-2) & 5\cdot2+(-2)\cdot3\\ 
2\cdot4+3\cdot1 & 2\cdot5+3\cdot(-2) & 2\cdot2+3\cdot3
\end{pmatrix}=\begin{pmatrix}
17 & 18 & 11\\ 
18 & 29 & 4\\ 
11 & 4 & 13
\end{pmatrix}$ \\
$A^{T}A=\begin{pmatrix}
4\cdot4+5\cdot5+2\cdot2 & 4\cdot1+5\cdot(-2)+2\cdot3\\ 
1\cdot4+(-2)\cdot5+3\cdot2 & 1\cdot1+(-2)\cdot(-2)+3\cdot3
\end{pmatrix}=\begin{pmatrix}
45 & 0\\ 
0 & 14
\end{pmatrix}$

In [ ]:
A = np.array([[4,1],[5, -2],[2,3]])
print(f'A.T=\n{A.T}')
print(f'A*A.T=\n{np.dot(A,A.T)}')
print(f'A.T*A=\n{np.dot(A.T,A)}')

A.T=
[[ 4  5  2]
 [ 1 -2  3]]
A*A.T=
[[17 18 11]
 [18 29  4]
 [11  4 13]]
A.T*A=
[[45  0]
 [ 0 14]]


__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [ ]:
def multimatrix(a, b):
    a_rows = len(a)
    a_cols = len(a[0])
    b_rows = len(b)
    b_cols = len(b[0])
    if a_cols == b_rows:
        c = [[0]*b_cols for i in range(a_rows)]
        for i in range(a_rows):
            for j in range(b_cols):
                for k in range(a_cols):
                    c[i][j] += a[i][k] * b[k][j]
        return np.array(c)
    else:
        return f'Число столбцов матрицы  𝐴  не равно числу строк матрицы  𝐵. Поизведение не может быть определено!'


A = np.array([[1,7],[3, -6],[2, -1]])
B = np.array([[0,5],[2, -1]])

print(multimatrix(A, B))



[[ 14  -2]
 [-12  21]
 [ -2  11]]


# Часть 2

__1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$
$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix}=sin x\cdot sin x - (-cos x)\cdot cos x= sin^2x+cos^2x=1$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
Определитель матрицы треугольного вида равен произведению элементов, стоящих на ее главной диагонали: \\
$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};=4\cdot5\cdot9=180$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}$$
$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}=1\cdot\begin{vmatrix}
5 & 6\\ 
8 & 9
\end{vmatrix};-2\cdot\begin{vmatrix}
4 & 6\\ 
7 & 9
\end{vmatrix};+3\cdot\begin{vmatrix}
4 & 5\\ 
7 & 8
\end{vmatrix}=5\cdot9-6\cdot8-2\cdot(4\cdot9-6\cdot7)+3\cdot(4\cdot8-5\cdot7)=0$


In [ ]:
a=np.array([[4,2,3],[0,5,1],[0,0,9]])
b=np.array([[1,2,3],[4,5,6],[7,8,9]])

print(f'Определитель для б: {np.linalg.det(a)}')
print(f'Определитель для в: {np.linalg.det(b):.0f}')

Определитель для б: 180.0
Определитель для в: 0


__2.__ Определитель матрицы $A$ равен $4$. Найти:



   а) $det(A^{2})=det(AA)=det(A)\cdot det(A)=4\cdot4=16$;
    
   б) $det(A^{T})=det(A)=4$;
    
   в) $det(2A)=2det(A)=2\cdot4=8$.

__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

Если две строки (столбца) матрицы линейно зависимы, то определитель этой матрицы равен нулю. В нашем случае вторая строка матрицы равна первой умноженной на $-2$,таким образом определитель данной матрицы равен нулю -- матрица вырожденная.

In [ ]:
a=np.array([[-2,7,-3],[4,-14,6],[-3,7,13]])
np.linalg.det(a)

0.0

__4.__ Найти ранг матрицы:


   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix}$ \\
3 строка является суммой первых двух, ее можно отбросить. \\
$\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1
\end{pmatrix}$ \\
Из 2 строки вычитаем 1. \\
$\begin{pmatrix}
1 & 2 & 3\\ 
0 & -1 & -2
\end{pmatrix}$ \\
Ранг матрицы равен 2.

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}$ \\
3 строка является суммой первых двух, ее можно отбросить. \\
$\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
2 & 3 & 5 & 6
\end{pmatrix}$ \\
Меняем строки местами. \\
$\begin{pmatrix}
2 & 3 & 5 & 6\\ 
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2
\end{pmatrix}$ \\
Ранг матрицы равен 3.

In [ ]:
a=np.array([[1,2,3],[1,1,1],[2,3,4]])
b=np.array([[0,0,2,1],[0,0,2,2],[0,0,4,3],[2,3,5,6]])

print(f'Ранг матрицы а = {np.linalg.matrix_rank(a)}')
print(f'Ранг матрицы б = {np.linalg.matrix_rank(b)}')

Ранг матрицы а = 2
Ранг матрицы б = 3
