1. Найти с помощью NumPy SVD для матрицы

$$\begin{pmatrix}
1 & 2 & 0\\ 
0 & 0 & 5\\ 
3 & -4 & 2\\ 
1 & 6 & 5\\ 
0 & 1 & 0
\end{pmatrix}.$$

In [2]:
import numpy as np

A = np.array([[1,2,0],[0,0,5],[3,-4,2],[1,6,5],[0,1,0]])
print(f'Матрица A:\n{A}')

Матрица A:
[[ 1  2  0]
 [ 0  0  5]
 [ 3 -4  2]
 [ 1  6  5]
 [ 0  1  0]]


In [13]:
U, d, V_t = np.linalg.svd(A)

V = V_t.T

D = np.zeros_like(A, dtype=float)
D[np.diag_indices(min(A.shape))] = d

print(f'Матрица U:\n{U.round(5)}\nМатрица D:\n{D.round(5)}\nМатрица V:\n{V.round(5)}')

Матрица U:
[[ 0.17057  0.15681 -0.53078 -0.79905 -0.16158]
 [ 0.39287 -0.52934  0.61348 -0.43376  0.03082]
 [-0.14366 -0.82449 -0.52379  0.1405   0.074  ]
 [ 0.88844  0.06074 -0.24655  0.37756 -0.06043]
 [ 0.08125  0.10832 -0.08231 -0.10525  0.98174]]
Матрица D:
[[8.82487 0.      0.     ]
 [0.      6.14061 0.     ]
 [0.      0.      2.53272]
 [0.      0.      0.     ]
 [0.      0.      0.     ]]
Матрица V:
[[ 0.07116 -0.36738 -0.92735]
 [ 0.71702  0.66514 -0.20848]
 [ 0.69341 -0.65009  0.31075]]


In [12]:
# Проведем проверку
print(np.dot(np.dot(U, D), V.T).round(5))

[[ 1.  2.  0.]
 [ 0. -0.  5.]
 [ 3. -4.  2.]
 [ 1.  6.  5.]
 [-0.  1. -0.]]


2. Для матрицы из предыдущего задания найти:

    а) евклидову норму;
    
    б) норму Фробениуса.

In [18]:
euclid_norm = np.linalg.norm(A, ord=2, axis=None, keepdims=False)
print(f'Евклидова норма: {euclid_norm:.5f}')

Евклидова норма: 8.82487


In [19]:
# Проведем проверку
euclid_norm.round(5) == D[0][0].round(5)

True

In [22]:
frobenius_norm = np.linalg.norm(A, ord='fro', axis=None, keepdims=False)
print(f'Норма Фробениуса: {frobenius_norm:.5f}')

Норма Фробениуса: 11.04536


In [32]:
# Проведем проверку
summa = 0
for i in range(0, len(D[0])):
    summa += D[i][i]**2
test_frobenius_norm = summa**0.5
test_frobenius_norm == frobenius_norm

True